#!/usr/bin/env bash
# This bash script displays "To infinity and beyond" indefinitely with
#+ a sleep in between each iteration
#  It displays "I am invincible!!!" in between each iteration

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
