#!/usr/bin/env bash
# This will indefinitely write "I am alive" to the file /tmp/my_process.
#   It will pause two seconds in between each message

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
