#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

# initialize counter
counter=1

while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
