#!/usr/bin/env bash
# A script that loops through 1 to 10 using while

# initializing i
i=1

while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
